id: model1

model:
  name: 3cnnlayer_3fclayer_128
  params:
    num_classes: 10
    conv_channels: [3, 32, 64, 128]
    fully_connected_layers: [128, 128]
    kernel_size: 3
    pool_kernel: 2
    use_batchnorm: True
    dropout_rate: 0.5
    activation_function: ReLU
    pooling: MaxPool2d
    norm_type: 2
    output_size: 32

training:
  dataset: CIFAR10
  data_augmentation: 
    random_crop: True
    horizontal_flip: True
  batch_size: 128
  num_epochs: 500
  patience: 20
  min_improvement: 0.01
  learning_rate: 1e-3
  weight_decay: 1e-4
  num_workers: 2
  shuffle: True
  optimizer: Adam
  

testing:
  batch_size: 100
  shuffle: False

image:
  im_height_width: 32